<div class="social-group">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-sm-12 col-xs-12">
				<?php echo $this->getLayout()->createBlock('Plazathemes\LatestTweet\Block\LatestTweet')->setTemplate('latesttweet.phtml')->toHtml();?>
			</div>
			<div class="col2 col-md-6 col-sm-12 col-xs-12">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('social')->toHtml();?>
			</div>
		</div>
	</div>
</div>