<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter">
	<h2 class="title"><?php echo __('Sign up for send newsletter')?></h2>
	<p class="des"><?php echo __('You can be always up to date with our company new!')?></p>
	<div class="content">
		<form class="form subscribe"
			novalidate
			action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
			method="post"
			data-mage-init='{"validation": {"errorClass": "mage-error"}}'
			id="newsletter-validate-detail">
			<div class="field newsletter">
					<label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ //echo __('Sign Up for Our Newsletter:') ?></span></label>
					
					<div class="control">
						<input name="email" type="email" id="newsletter"
									placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
									data-validate="{required:true, 'validate-email':true}"/>
						
					</div>
					<div class="actions">
						<button class="action subscribe" title="<?php /* @escapeNotVerified */ echo __('Send Email') ?>" type="submit">
							<span><?php /* @escapeNotVerified */ echo __('Send Email') ?></span>
						</button>
					</div>
			</div>
		</form>
	</div>
</div>
